### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#11]
If you are reporting an issue, or have a question regarding the search, please indicate the following 
in addition to describing the problem:

The record type in question (mark  all if it pertains to all, or is a combined search issue)
- [x ] EDS
- [ ] Catalog (includes ContentDM)
- [ x] LibGuides

This problem/question pertains to 
- [ ] searching/queries (example, advanced searches, how to do proximity search, etc..)
- [ x] Result sets.  (browse or search results)

**Comment by dallison1** [comment]
Looks like the LibGuides are interfering with the EDS load.  When I do a search on Mikes site it brings back 20 entries, but on the new site with the LibGuides only the first 10 display with a second EDS group below the libguides with a eds loading icon that never finishes

**Comment by srickel1** [comment]
Those are just differences in our settings files on the limits.  The group below the LibGuides is actually the old EBSCOhost , but I haven't had time to update the configuration file.

**Comment by srickel1** [comment]
The EBSCO search is working again.   The OCLC Illiad links now work correctly as well.
