### ISSUE TITLE
Journal of Zoology

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#12]
If you are reporting an issue, or have a question regarding the search, please indicate the following 
in addition to describing the problem:

  http://vufind-dev.unl.edu/vufind/Record/b4286440
The title Journal of Zoology b42864409  has multiple 856 fields in the catalog with one record.  When I search Vufind there are two records with no 856 fields.  It looks like it got merged at time point but hasn't been synced, but why no links?

It appears that the MARC export I did doesn't include the fields.  I have an example if you want to look at it.  However I also have an example where it did include the 856.

**Comment by srickel1** [comment]
I found one Journal of Zoology in vufind that matches the b# you gave, and yes it does not have the 856 fields because it looks like the catalog was updated 2-12-16 and we don't have the syncing automated yet, since we are still working through problems with the harvesting/creation of marc records.

I don't know how or what is being used to provide them in the cases of no 856 field. I'll leave this open for a bit to see if we answered the question.

**Comment by srickel1** [comment]
I re-harvested the entire catalog, and I find the record mentioned in vufind still has no 856 fields, but I see that the bib record in the catalog also does not have any.  It was updated 3-21-16.

**Comment by dallison1** [comment]
It is true the record doesn't have 856 fields, the urls are stored in the resource records:
e10000124
e20000483
31001133x
e10013830
The URL is in the checkin record linked to the ERM record for example c3224090 see SLKe10013830

So every month a new coverage file from Serial Solutions is loaded, which up[dates the ERM record when in turn updates holdings information on checkin records linked to the ERM record, which then are displaced in the catalog.  

How we are going to handle these links is a big question.!!!

**Comment by dallison1** [comment]
Actually the URL are stored in the checkin record that is linked to the ERM record - miswrote above.

**Comment by srickel1** [comment]
found the 856's for erm records in the holding_record_erm_holding table/view. 
The following query illustrates how to get it 

`select bib_view.record_type_code, bib_view.record_num,bib_view.bcode1,bib_view.bcode2,bib_view.bcode3, bib_view.title,holding_record_erm_holding.*
FROM sierra_view.bib_view 
LEFT JOIN sierra_view.bib_record_holding_record_link ON bib_record_holding_record_link.bib_record_id=bib_view.id
LEFT JOIN sierra_view.holding_record_erm_holding ON holding_record_erm_holding.holding_record_id=bib_record_holding_record_link.holding_record_id
WHERE bib_view.record_num=4306847`

**Comment by srickel1** [comment]
fixed with the commit [ecc3357](https://github.com/unl-libraries/marc_harvest/commit/ecc335744b8ee8be0fad33d74635a0ac3de4b5bb) of the marc_harvest code.  That merged the 856's from ERM records into the marc record we download and load into vufind.  Will reharvest to correct all these.
