### ISSUE TITLE
bib record that is cut-off

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#16]
This record is being truncated:  http://cors1204.unl.edu/vufind/Record/4313407

It is also truncated in Sierra so I wonder if you can even get the full record using the API?  This was II's answer to our question:
Your observation about the headings that come further down in the list of 700 fields is right on the money. Apparently there's some architectural limit to the number of fields and index entries per field group in a record, beyond which all bets are off for expected behavior. The limits are >127 fields or >62 index entries, and sure enough, what you report starts happening with 700 field #63 (the one for Rachmaninoff, Sergei, 1873-1943. Preludes, piano, op. 32. No. 8). The oddness here is that the system has no trouble indexing these entries -- it just can't reliably pull them out of the index for proper display in WebPAC. It's not just in record browses and "best title"; it happens in index browses as well, although the manifestation is slightly different.

Unfortunately, I first learned of this limitation when reporting the index browse issue, and was told by Product Development that although the limitation is something that should be reevaluated at some point, they were not able to devote resources to doing so anytime soon; that bug report was closed as "won't fix," and the next report I tried to submit was dismissed with what amounted to a "don't bother." Long way of saying that there's nothing that can be done to correct this situation, and not a lot of hope that that will ever change.

**Comment by srickel1** [comment]
What is being truncated? I'm not sure I follow this ticket as to the issue, or what we hope to do to resolve it.
