### ISSUE TITLE
Reserves import error

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#17]
@mlitwa  The code in the ILS Sierra driver (ours is https://github.com/unl-libraries/vufind/blob/master/local/module/VuFind/src/VuFind/ILS/Driver/UNLSierra.php - line 319)  throws errors on the coursenum variable is undefined.   Need help figuring this out. 

`public function findReserves($course, $instructor, $department)
    {
        try {
            if ($course != null) {
                $coursenum = $course;
            } elseif ($instructor != null) {
                // This deals with the "fake ID" hack explained in the getInstructors
                // function
                $instructor = explode("-", $instructor);
                $coursenum = $instructor[0];
            }
            $query = "SELECT DISTINCT bib_view.record_num "
                . "FROM sierra_view.bib_view "
                . "INNER JOIN sierra_view.bib_record_item_record_link "
                . "ON (bib_view.id = bib_record_item_record_link.bib_record_id) "
                . "INNER JOIN sierra_view.course_record_item_record_link "
                . "ON (course_record_item_record_link.item_record_id = "
                . "bib_record_item_record_link.item_record_id) "
                . "INNER JOIN sierra_view.varfield_view "
                . "ON (course_record_item_record_link.course_record_id = "
                . "varfield_view.record_id) "
                . "WHERE varfield_view.record_num = $1;";
            $results = pg_query_params($this->db, $query, [$coursenum]);
            while ($resultArray = pg_fetch_row($results)) {
                $bareNumber = $resultArray[0];
                $fullNumber = $this->createFullId($bareNumber);
                $reserves[]['BIB_ID'] = $fullNumber;
            }
            return $reserves;
        } catch (\Exception $e) {
            throw new ILSException($e->getMessage());
        }
    }`

I tracked the call to this function to line 152 in the master code of vufind utilities for reserves 
(https://github.com/vufind-org/vufind/blob/master/module/VuFindConsole/src/VuFindConsole/Controller/UtilController.php) says:
`try {
                // Connect to ILS and load data:
                $catalog = $this->getILS();
                $instructors = $catalog->getInstructors();
                $courses = $catalog->getCourses();
                $departments = $catalog->getDepartments();
                $reserves = $catalog->findReserves('', '', '');
            } catch (\Exception $e) {
                return $this->indexReservesHelp($e->getMessage());
            }`

I can't figure how the empty string parameters are supposed to work in this case.

**Comment by mlitwa** [comment]
In the UtilController, the courses, departments, and reserves should probably be passed to the findReserves function, Don't know if this will solve the issue, but at least the data we need should be going to the right place

**Comment by srickel1** [comment]
Got this to work with loading a csv file, using the queries supplied in the controller in an external script.  It's not current and needs some cleanup for out of date records, but it worked.
