### ISSUE TITLE
alternate title breaks contentdm

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#20]
Views of contentdm records are broken.  The error log reports

`PHP Fatal error:  Call to undefined method VuFind\\RecordDriver\\SolrDefault::getAltTitles() in /usr/local/vufind2/themes/unl/templates/RecordDriver/SolrDefault/core.phtml on line 95`

Both servers report that the function exists in module/VuFind/src/VuFind/RecordDriver/SolrMarc.php

I can see alternate titles show up though on the regular catalog records, the error only is thrown on the image and multimedia records.  I would have suspected because they weren't stored as marc it would be an error, just not that error.

**Comment by mlitwa** [comment]
Added the function into the SolrDefault file, and seems to be working correctly now
