### ISSUE TITLE
include holdings

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#22]
Checkin records all start with a c and include holdings information.

**Comment by srickel1** [comment]
Want holdings information reflected on the record, not necessarily the checkin records ingested themselves.

**Comment by srickel1** [comment]
Examples to check when this is working....

for regular records - example:http://vufind-dev.unl.edu/vufind/Record/b1155397
and for Electronic (ERM) - example: http://vufind-dev.unl.edu/vufind/Record/b4286440

**Comment by srickel1** [comment]
This is NOT working yet - the above examples were posted here to remind me to check when completed.

**Comment by srickel1** [comment]
I have some preliminary results coming up for lib has information over in vufind-test.unl.edu
http://vufind-test.unl.edu/vufind/Record/b4286440 is an ERM example.
a few other bib records
b4291993
b1457940
b1242980

I have yet to map the location codes to readable values.
