### ISSUE TITLE
need to add webbridge button to catalog records

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#24]
Implement similar to classic catalog so the links appear like they do on bib records in the catalog.  They should display the call number locator, etc. in the vufind bib record

**Comment by dallison1** [comment]
Call number locator and 
This is for request deliver:
https://unl.illiad.oclc.org/illiad/illiad.dll/OpenURL?sid=UNLcat&genre=book&aulast=#@AULAST#&aufirst=#@AUFIRST#&title=#@TITLE#&callnumber=#@callnumber#&date=#@DATE#&pub=#@PUBLISHER#&edition=#@EDITION#&place=#@PLACE#&ESPNumber=#@OCLC Number#&isbn=#@ISBN#
and this is toFind in the nearest library by title:
http://0-partneraccess.oclc.org.library.unl.edu/wcpa/servlet/OpenUrl?sid=WorldCat&genre=book&title=#@TITLE#

**Comment by srickel1** [comment]
Call number locator is discussed in another ticket, as is request delivery.  I think this needs to be resolved not so much as 'duplicate webbridge' which we cannot do, but what specific functionality needs to be added that can work **based on the bib record information** available to us
