### ISSUE TITLE
add a-z list option

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#26]
Can you think of a way to get a searchable version of this added:
http://library.unl.edu/search/?searchtype=y&SORT=D&searcharg=*

**Comment by srickel1** [comment]
Do you mean to index the eresources?  Haven't we already discussed this?  Duplicate of #6

**Comment by dallison1** [comment]
No, I'm wondering if there is a better way to integrate this information - a complete list instead of using the e-resources page.  Since that can't be harvested this might be an alternate way to integrate the individual titles.

**Comment by srickel1** [comment]
done with Mike's update to show subject facets on front page.
