### ISSUE TITLE
Add functionality so searches will also bring back a link suggestion

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#27]
This is similar to Pixel so when someone enters a search if it matches an entry in "pixe;" a suggestion would appear along with the search results.

**Comment by srickel1** [comment]
I'd like to hear from @dallison1 what to do with remaining open issues in vufind such as this one. We need to know whether we need to continue researching and trying to accomplish whatever is in the ticket.

**Comment by dallison1** [comment]
not a priority
