### ISSUE TITLE
add Web of science to EBSC search results

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#28]
There is an API for Web of Science: http://wokinfo.com/products_tools/products/related/webservices/ws_faq/?utm_source=false&utm_medium=false&utm_campaign=false

**Comment by srickel1** [comment]
I'd like to hear from @dallison1 what to do with remaining open issues in vufind such as this one. We need to know whether we need to continue researching and trying to accomplish whatever is in the ticket.

**Comment by dallison1** [comment]
go ahead and close
