### ISSUE TITLE
replace icons for Ebsco results

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#30]
- [x] Use  attached JournalArticle.png for article or journal article
  ![journalarticle](https://cloud.githubusercontent.com/assets/11300102/15324618/cf03ceda-1c0c-11e6-83d4-0f497dd7ddc5.png)
- [ ] Use article.png for serial and Article in a periodical
- [x] Use TradePubliationArticle.png for Company report
- [x] Use Report.png for product review
- [x] Use Thesis.png for case study
- [x] Use attached opinion.png for opinion and commentReply 
  ![opinion](https://cloud.githubusercontent.com/assets/11300102/15329146/3ee32754-1c1d-11e6-961d-6c1ce9ea90a8.png)
- [x] Use BookChapter.png for Chapter

**Comment by srickel1** [comment]
Note - the images pull up based on the record format, so I have the peer reviewed image coming up for:JournalArticle.png and Article.png
Copied Thesis.png to CaseStudy.png
Uploaded Opinion.png for the Opinion type
copied BookChapter.png to Chapter.png

Need examples of Serial, article in a periodical, company report, product review and comment reply to match those.

**Comment by srickel1** [comment]
starting creating virtual links to some of the ones in multiple uses.  Company Report now works.

**Comment by srickel1** [comment]
Serial is ok now too.

**Comment by dallison1** [comment]
- [ ] proceedings
  
  Use this one for proceeding for EBSCO results
  ![proceedings](https://cloud.githubusercontent.com/assets/17299921/15610049/eb3ddabc-23e8-11e6-85a2-5864fe1837fc.png)

**Comment by dallison1** [comment]
- [x] use journalarticle icon also for format "article"
  These appear to be peer reviewed as well so use the same graphic

**Comment by dallison1** [comment]
- [ ] Use the opinions icon for column/opinion format.

**Comment by dallison1** [comment]
- [ ] Use this icon for abstract format 
  ![abstract](https://cloud.githubusercontent.com/assets/17299921/15610184/9246b9aa-23e9-11e6-8183-f5450e111b7b.png)

**Comment by srickel1** [comment]
Please note above comments that some of these have already been noted and taken care of.  Also can we have example records so we can tell if we matched correctly?

**Comment by dallison1** [comment]
- [x] example of swot analysis- http://vufind-dev.unl.edu/vufind/EITRecord/97479062 use report.png for this
- [x] format: contribution - use proceedings icon hhttp://vufind-dev.unl.edu/vufind/EITRecord/PHL2327534
- [x] format essay http://vufind-dev.unl.edu/vufind/EITRecord/115387325 use article.png
- [ ] format: article in a periodical http://vufind-dev.unl.edu/vufind/EITRecord/2013-19135
- [x] format comment/reply http://vufind-dev.unl.edu/vufind/EITRecord/2016-09265-012 use opinion.png
- [x] format review-book http://vufind-dev.unl.edu/vufind/EITRecord/2015-39699-021 use BookReview.png also see http://vufind-dev.unl.edu/vufind/EITRecord/2015-47042-013

**Comment by dallison1** [comment]
- [x] format erratum/correction http://vufind-dev.unl.edu/vufind/EITRecord/2013-15740-001 use NewspaperArticle.png

**Comment by dallison1** [comment]
- [x] reference entry ![info](https://cloud.githubusercontent.com/assets/17299921/15616294/61a030aa-2408-11e6-8390-cdd459d695d7.png)
  example at http://vufind-dev.unl.edu/vufind/EITRecord/TE034000

**Comment by dallison1** [comment]
- [x] editorial http://vufind-dev.unl.edu/vufind/EITRecord/96311306 
  ![editorial](https://cloud.githubusercontent.com/assets/17299921/15616430/5200af16-2409-11e6-9217-946ab5008fa8.png)

**Comment by dallison1** [comment]
- [x] product review example
  http://vufind-dev.unl.edu/vufind/EITRecord/110139171

**Comment by dallison1** [comment]
- [x] conference paper http://vufind-dev.unl.edu/vufind/EITRecord/27204151  use proceedings.png

**Comment by dallison1** [comment]
- [ ] speech http://vufind-dev.unl.edu/vufind/EITRecord/27204151
  ![speech](https://cloud.githubusercontent.com/assets/17299921/15616664/d5741242-240a-11e6-9e44-31372981ab6e.png)

**Comment by dallison1** [comment]
- [x] literary criticism http://vufind-dev.unl.edu/vufind/EITRecord/34455123
  ![litcrit](https://cloud.githubusercontent.com/assets/17299921/15616819/a171f594-240b-11e6-9b9a-c18ac7eeb209.png)

**Comment by dallison1** [comment]
- [x] transcript http://vufind-dev.unl.edu/vufind/EITRecord/110310370
  ![transcript](https://cloud.githubusercontent.com/assets/17299921/15616912/1f83c296-240c-11e6-8c35-504a49def76f.png)

**Comment by srickel1** [comment]
The example for Speech is a Conference Paper.  Do you want Conference Papers to use that icon?

**Comment by srickel1** [comment]
I've checked off the ones I'm sure of.  Can't figure out what it expects for "Article in a periodical" yet.  Haven't seen a proceeding or abstract or column/opinion to verify those are showing correctly yet.

**Comment by dallison1** [comment]
No, use this one for speech

Thanks,
DeeAnn

**Comment by dallison1** [comment]
- [ ] Found another format Thesis or dissertaiton:
  http://eds.a.ebscohost.com/ehost/detail/detail?sid=ef43c4c4-442f-40bc-9fbb-ec255672af13%40sessionmgr4002&vid=0&hid=4102&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl#AN=2015-013705&db=geh 

http://vufind-dev.unl.edu/vufind/EITRecord/2015-034181
 you can use the dissertation icon you already have

**Comment by dallison1** [comment]
- [ ] need format for map:
  http://vufind-dev.unl.edu/vufind/EITRecord/2014-091544
  ![map](https://cloud.githubusercontent.com/assets/17299921/15711133/683a2b82-27d2-11e6-8d54-31906009d38b.png)

**Comment by dallison1** [comment]
- [ ] Poem
  http://vufind-dev.unl.edu/vufind/EITRecord/114855132
  ![poetry](https://cloud.githubusercontent.com/assets/17299921/15719106/0ae41c50-27f4-11e6-87fd-2621e6238952.png)

**Comment by dallison1** [comment]
- [ ] This essay is displaying a peer reviewed article:
  http://vufind-dev.unl.edu/vufind/EITRecord/112531596
  Lets change this to: essay
  ![essay](https://cloud.githubusercontent.com/assets/17299921/15754628/a2684388-28be-11e6-9434-67baedcddc9b.png)

**Comment by srickel1** [comment]
I stopped working on this as no one seems to want icons anyway
