### ISSUE TITLE
please add as the graphic for abstract format in the Ebsco layer

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#31]
![abstract](https://cloud.githubusercontent.com/assets/17299921/15543168/7a0cfca0-2259-11e6-932e-1debfcbc6e63.png)
This is the icon to display for abstracts that come up in Ebsco.  Also use for Abstract Only

**Comment by srickel1** [comment]
cover images are retrieved based on the format of the record.  Please provide examples of the record so we can match it up.

Duplicate of ticket #30.  Please update that ticket with these requests.
