### ISSUE TITLE
use this icon for article in a periodical

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#33]
![journalarticle](https://cloud.githubusercontent.com/assets/17299921/15543350/23b626dc-225a-11e6-9854-9ce5e41631f0.png)

These appear to be peer reviewed as well so use the same graphic (see attached)

**Comment by srickel1** [comment]
cover images are retrieved based on the format of the record.  Please provide examples of the record so we can match it up.

**Comment by srickel1** [comment]
duplicate of another ticket so closing
