### ISSUE TITLE
icon for proceeding

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#34]
![proceedings](https://cloud.githubusercontent.com/assets/17299921/15543496/c110cfb8-225a-11e6-8259-ad0093473850.png)
Use this one for proceeding for EBSCO results

**Comment by srickel1** [comment]
cover images are retrieved based on the format of the record.  Please provide examples of the record so we can match it up.

Duplicate of #30. Please update that ticket with all further icon requests.
