### ISSUE TITLE
Getting an error on this record

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#36]
http://vufind-dev.unl.edu/vufind/EITRecord/676931-72  note this is for an abstract also.

**Comment by srickel1** [comment]
Can you get to the record in Ebsco? How did you get to the record in vufind? Does it show up in search results ok, just not when you click on it?

**Comment by dallison1** [comment]
this search will bring up the page with the bad link - every one for abstract only has the same error:
http://vufind-dev.unl.edu/vufind/EIT/Search?lookfor=discovery+&type=TX&page=35

**Comment by dallison1** [comment]
Yes it dispays in EBSCO

**Comment by dallison1** [comment]
It seems like all the abstract only formats are giving this error, also they don't have titles but they are in EBSCO

**Comment by dallison1** [comment]
Got the same error - it seems to be for anything that says title not available:
http://vufind-dev.unl.edu/vufind/EITRecord/2006-058123

They all seem to be OK in EBSCO

**Comment by srickel1** [comment]
Dug a little deeper in debug mode and found that the first 3 I looked at had multiple titles being sent along.  As seen here in this sample of the array returned under the 'atl' :

```
[artinfo] => SimpleXMLElement Object
           (
            [ui] => Array
                      (
                            [0] => 2014-036170
                            [1] => 10.1016/j.geomorph.2013.06.011
                          )
               [ppf] => 62
                 [ppct] => 20
                 [pages] => 62-81
                  [tig] => SimpleXMLElement Object
                      (
                            [atl] => Array
                                 (
                                     [0] => Impacts of Hurricane Ike on the beaches of the Bolivar Peninsula, TX, USA
                                      [1] => Coastal geomorphology and restoration
                        )

                     )
```

**Comment by srickel1** [comment]
Upgrading to version 3.0.1 did not fix this problem.

**Comment by srickel1** [comment]
I'd like to hear from @dallison1 what to do with remaining open issues in vufind such as this one. We need to know whether we need to continue researching and trying to accomplish whatever is in the ticket.

**Comment by dallison1** [comment]
go ahead and close I can't replicate this.
