### ISSUE TITLE
index journal titles

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#38]
This is the index rule for journal title so we need to index the 222 field subfields abpn in a separate index.
BIBLIOGRAPHIC   OTHER TI(u)     222     KEEP abpn   JOURNAL TITLE(j)
subfields are:
a key title
b qualifying information (like a place name)
p part name
n number
for example: 245    00$aJournal of polymer science.$nPart B,$pPolymer letters.

Here is an example marc record:
LEADER  01291cas a2200337I 4500
001     2354797
035             |a .b11939539 
998             |c 1990-02-12 00:00:00-06  |d a  |e s  |f t 
010             |a 42016492 //r65 
022     0       |a 0010-0870 
040             |a TRN  |c TRN  |d UCU  |d COO  |d YUS  |d MUL  |d COO  |d NSD  |d LDL 
042             |a nsdp 
049             |a LDLL  |a [FACULTY] LDLS 
050     0   0   |a Z671  |b .C6 
222         0   |a College & research libraries 
245     0   0   |a College & research libraries 
246     3   3   |a College & research libraries, C&RL 
260             |a Fulton, Mo.,  |b American Library Association,  |c [1939- 
300             |a v.  |b ill., plans, diagrs.  |c 26 cm 
310             |a Bimonthly, 1956- 
321             |a Quarterly, 1939-55 
362     0       |a v. 1- Dec. 1939- 
500             |a Vol. 54, no. 2 (1993) includes an article by Joan Giesecke. 
520             |a List of members of the association in v. 1- 
550             |a Official organ of the Association of College and Research Libraries (called 1939-57, Association of College and Reference Libraries) 
650         0   |a Library science  |x Periodicals 
700     0       |a Giesecke, Joan 
710     2       |a Association of College and Research Libraries 
910             |a ))RRL110178J##2354797 
999             |a LINKED TITLE: LOVE 07-03-00 me 
907             |b spec  |l Special Collections  |b ldrf  |l LDRF  |b love  |l Love Library  |b dof  |l DOCS Facility  |b multi

**Comment by srickel1** [comment]
You want it searchable as a journal title, and not under the title?  So it only comes up under all field searches, or if you choose "Journal title" in the drop down?

Is this a single value field- not repeatable - one 222 field per record if any?

**Comment by dallison1** [comment]
The 222 field is repeatable.  I would like a separate index for journal title *include in the drop down)  as well as having it indexed in the title and keyword.

DeeAnn

**Comment by srickel1** [comment]
What does
BIBLIOGRAPHIC OTHER TI(u) 222 KEEP abpn JOURNAL TITLE(j)

mean?

**Comment by dallison1** [comment]
It means the 222 is in the bibliographic record stored in the title field of Sierra, keep abpn subfields, and index in the j and u indexes (also Sierra).

So the important info for you is to keep the abpn subfields

**Comment by srickel1** [comment]
ok - the 222 field is indexed as 'container_title' in vufind on vufind-dev.unl.edu.  That field is the only field the JournalTitle search looks at.  It shows up on the record as "Published in..." which can be changed or suppressed from display as needed.
