### ISSUE TITLE
099 call numbers seemed to be indexed as LC call numbers

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#40]
Not sure how the call numbers are indexed but it appears that 099 are being included with 050 and 090 as lc call numbers.  This makes the browse by call numbers a problem.  We probably need to look into this at some point.

**Comment by srickel1** [comment]
And what are 099 supposed to be indexed as?

**Comment by dallison1** [comment]
Let’s leave this for now.

DeeAnn
