### ISSUE TITLE
Update CSS to v3.1

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#43]
The compiled CSS for the unl theme needs to be updated to version 3.1
This will hopefully fix a number of lightbox issues where the text overflows the boxes and the exclusion links are missing from the filters

**Comment by srickel1** [comment]
@mlitwa I noticed a small thing in the searchbox - the border for the tabs is green while the rest is red.

**Comment by mlitwa** [comment]
Fixed that color issue

**Comment by srickel1** [comment]
Excellent!  Was there anything else left in the CSS to take care of? It's looking pretty good.

**Comment by mlitwa** [comment]
Don't think so

**Comment by srickel1** [comment]
Guess that means this is done.
