### ISSUE TITLE
Changes to make from the communication group

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#46]
- [x] Can the call number display in the holdings tab on the bib record?
- [x] Can you change the main page display so that Browse by Call Number, Browse by Language and Browse by Subjects section is below Search options, Find More and Need Help?
- [x] Change Database tab to Database List
- [x] Change Ask a Librarian to ASKus and have the link go to libraries.unl.edu/askus-1
- [x] Remove FAQs (doesn’t go anywhere)
- [ ] , Joanie is going to supply some working that would go in the red band across the top in the red band, something like “The Libraries primary server is down from Dec. 21-22.  You can still search for books and databases using this emergency catalog.  Links to licensed resources like database and e-journals will only work if you are searching from on-campus.”

**Comment by srickel1** [comment]
Call number displayed as part of main record details, since holding tab is disabled while catalog is down....

**Comment by srickel1** [comment]
Tentatively saying that the second option is done.  Those items were actually in the footer (and still are right now) so I moved them into the searchbox form element.  The items do not appear in the advanced search form, but elsewhere the regular searchbox appears. The code for that is in commit 24acc8dabe694e72b914c41b5bcdb2ef797a3c22 of the 3.1 branch

The footer will need to be altered then, if we decide we need something there.

**Comment by srickel1** [comment]
Oops - copied the wrong footer information over.  The correct information is in commit d1bada59298c0d550772174f8527a0bf08706216

**Comment by srickel1** [comment]
While we never got any special wording for the down time, now that it is over  will consider this ticket done.
