### ISSUE TITLE
I got no results when I put terms in and tried to limit by Geography & Maps. 

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#53]
Sample URL http://vufind-dev.unl.edu/vufind/Search/Results?hiddenFilters%5B%5D=collection%3AResource+records&sort=relevance&join=AND&lookfor0%5B%5D=lancaster&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=AND&filter%5B%5D=%7Etopic_facet%3A%22Geography+%26+Maps%22&illustration=-1&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=

(Reported by Sue Ann Gardner)

**Comment by srickel1** [comment]
I'm not sure I follow how this search happened.  It looks like she might have been on the database list tab, which already filters things to the resource records, and then tried to limit by a facet that I can't seem to find.    No results is not necessarily a problem, unless someone believes there should be matches for that search.  

Since the resource record filter is a hidden filter (used to provide it as a tabbed option), it doesn't show to the user it's in use there.

**Comment by srickel1** [comment]
I'd like to hear from @dallison1 what to do with remaining open issues in vufind such as this one. We need to know whether we need to continue researching and trying to accomplish whatever is in the ticket.

**Comment by dallison1** [comment]
I think this is OK go ahead and close.
