### ISSUE TITLE
No link to file in record 

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#54]
After clicking on an author’s name to see items for that person (actually, me), for one item “Hot potato: who will end up paying for open access? [slides]” by Sue Ann Gardner, Published 2009-09-30T07:00:00Z” the little “pdf” icon did not appear. Instead, there was a long string in the same kind of box: “vnd.openxmlformats-officedocument.presentationml.presentation.” The little “pdf” icon was on all of the others and I was able to access the ones that I tried to access. I could not access the one with the weird icon

URL: http://vufind-dev.unl.edu/vufind/Author/Home?author=Gardner%2C+Sue+Ann

(reported by Sue Ann Gardner)

**Comment by srickel1** [comment]
The weird icon is actually just something that reflects the format of the record.  As it came from digital commons, `vnd.openxmlformats-officedocument.presentationml.presentation`  is  apparently the format.  We might be able to map that to something else, if we are know what that is supposed to be.

The link was missing because it was formatted different than all the other links and the indexing process missed seeing that it was a link to content.  I have fixed that and reindexed that record which now shows the link. 
Note: these links are going directly to the content, NOT the digital commons record.

**Comment by srickel1** [comment]
According to@dallison1, this needs to be followed up with Margaret Mering on possible formats allowed in Digital Commons.  Assuming this is a valid ticket to pursue.

**Comment by dallison1** [comment]
fixed.
