### ISSUE TITLE
I don’t see any equivalent to the “request delivery” button in Encore

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#55]
(Reported by Anna Wigtil)

**Comment by srickel1** [comment]
This may be dependent on the catalog being up, as I believe that works with holdings.

**Comment by srickel1** [comment]
I'd like to hear from @dallison1 what to do with remaining open issues in vufind such as this one. We need to know whether we need to continue researching and trying to accomplish whatever is in the ticket.

**Comment by dallison1** [comment]
This requires WebBridge unless we can create a link that would autopopulate an ill form directly.  I consider this a low priority unless it is easy to do.
