### ISSUE TITLE
I want to see a link to the call number locator.

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#57]
(Reported by Anna Wigtil)

**Comment by srickel1** [comment]
If it is decided to link to the call number locator - where would we put it?

**Comment by srickel1** [comment]
I've added links to the locator map in the "Find more" section under the search bar, and the call numbers link to the locator map page.  I can work on linking them to a search to resolve to the correct map as well, unless we still want that in a menu on the right

**Comment by dallison1** [comment]
If you can get it to resolve to the map that would be great.  I would like to see listed with the menu bar on the bib record, after export record – something like Find this”

**Comment by srickel1** [comment]
I  can't get this to resolve to the maps without the sid information provided from the catalog, so the only option is provide generic links to the main locator map page. That is done.
