### ISSUE TITLE
The link in this record goes to an EBSCO error page.

### ISSUE THREAD

**Issue by srickel1** [unl-libraries/vufind#59]
When I search “EBSCO” in the main catalog search instead of the database search, the first results is “EBSCO online” (http://vufind-dev.unl.edu/vufind/Record/b3216435) .

 The link in this record goes to an EBSCO error page.

 It would be nice if the relevance search could bring up Academic Search Premier or the page listing all EBSCO databases as the first result in both the catalog search and database search.
(reported by Anna Wigtil)

**Comment by srickel1** [comment]
Another cataloging issue.  This is the link from Sierra. 

I don't think we could do the second part.

**Comment by srickel1** [comment]
I'd like to hear from @dallison1 what to do with remaining open issues in vufind such as this one.  We need to know whether we need to continue researching and trying to accomplish whatever is in the ticket.

**Comment by dallison1** [comment]
It seems to be working - as there is no more error messages.  I would close this.
