### ISSUE TITLE
Have eresources go to the top of the results list

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#6]

**Comment by srickel1** [comment]
Right now the best way I could think of doing this is to separate them into their own search. Will need investigation.

**Comment by srickel1** [comment]
After review, we discovered that the eresources were not even ingested into vufind.

They have a .e#  as bib records have a .b#, so we will have to adjust our harvesting to make note of that.  

@mlitwa - What do you think is the best approach? To index them separately, or include them with the rest of the catalog and try to pull them out afterwards?

**Comment by srickel1** [comment]
- [x] Index eresources
- [ ] prioritize eresources ahead of all catalog results

**Comment by srickel1** [comment]
Trying to harvest the eresources web page full text as an option. see #19 for more information

**Comment by srickel1** [comment]
1,006 Eresources have been indexed into [vufind-dev](http://vufind-dev.unl.edu/vufind/Search/Results?type=AllFields&filter%5B%5D=collection%3A%22Resource+records%22) 
These have a format of "Electronic Resource" and belong to the collection "Resource records"
Remaining to do here is:
- [x] add the Authorized user field to the display
- [x] add the public note to the display
- [x] find a way to add this set as a tab or recommendation module

**Comment by srickel1** [comment]
These have a separate tab now, as a filtered result set, as can be seen in the searches.ini file. So I think this takes care of the issue.
