### ISSUE TITLE
implement phrase searching

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#7]
Multiple words should search as a phrase.

**Comment by srickel1** [comment]
Again, we need to know:
1.  which items this applies to.
2. Do you mean they should do a proximity search by default? (contains all the words in close proximity?)

Everything that shows up in a separate area (Catalog, EDS, LibGuides) has it own search options and strategies.  This makes creating a specialized search **in the keyword search box** an issue to do by default.  That's all left to the advanced searching capabilities found in each section.

Have you gone to the advanced search in each area? That might answer your questions

**Comment by dallison1** [comment]
Ideally they should all default to the same search pattern.  The phrase searching for example: “beginning historical research”   the goal is for all the searches to act the same way without going to advanced search.  I set EDS to use smartsearch, not sure what that means but there are other options.  I’m hoping we can find one that will be consistent across all searches.

**Comment by srickel1** [comment]
Since EDS is no longer an option, is this an issue or question still?
