### ISSUE TITLE
Add book covers using Google API

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#8]
here is the link to documentation: https://developers.google.com/books/docs/dynamic-links

**Comment by srickel1** [comment]
I think this will need discussion and is low priority.  I personally don't see the book covers useful in our records since we won't have very many of them to show.  This is more for the public libraries I should think

**Comment by srickel1** [comment]
I enabled this and there are a few coming up.  Not many, so I also copied over some basic icon images from to show for formats that do not have a cover.
