### ISSUE TITLE
Add export citation option for articles

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#9]

**Comment by srickel1** [comment]
by articles do you mean EDS? and export it how?  We'll need some specifications for how it is supposed to be exported.

**Comment by dallison1** [comment]
Yes, for the articles section, when you click on an article there isn’t any way to export to refworks, etc.  This is probably an EDS issue unless we can add something to the menu at the bottom.

**Comment by srickel1** [comment]
We'll need an answer from @dallison1 as to  whether this needs pursuing further, and if so, what more needs to be done, since the citations are available in the record views.
